# Generated by Django 4.2.3 on 2023-07-07 18:51

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('testblog', '0003_blogpagetag_blogpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='testblog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
