# Generated by Django 4.2.3 on 2023-07-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0005_alter_blogpagetag_content_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='postIntro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blogindexpage_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testblog.blogindexpage'),
            preserve_default=False,
        ),
    ]
