# Generated by Django 4.2.3 on 2023-07-08 06:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('taggit', '0005_auto_20220424_2025'),
        ('testblog', '0006_rename_intro_blogpage_postintro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='postIntro',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='blogindexpage_ptr',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='testblog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='testblog.blogpage'),
        ),
    ]
