# Generated by Django 4.2.3 on 2023-07-08 10:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('testblog', '0007_rename_postintro_blogpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='custom_title',
            field=models.CharField(default='sdfsdf', help_text='Overwrites the default title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.RichTextBlock())], default='sdfsdf', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='custom_title',
            field=models.CharField(default='sfsdfsdfsdf', help_text='Overwrites the default title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='testblog.blogindexpage'),
        ),
    ]
