# Generated by Django 4.2.3 on 2023-07-08 10:58

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0008_blogindexpage_custom_title_blogpage_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='testblog.blogpage'),
        ),
    ]
