# Generated by Django 4.2.3 on 2023-07-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0012_blogindexpagetag_blogindexpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogIndexPageTag',
        ),
    ]
