# Generated by Django 4.2.3 on 2023-07-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0013_remove_blogindexpage_tags_delete_blogindexpagetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
    ]
