# Generated by Django 4.2.3 on 2023-07-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0019_footerlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlinks',
            name='footer_link',
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='footer_link_text',
            field=models.CharField(default='/Crypto/', max_length=255),
            preserve_default=False,
        ),
    ]
