# Generated by Django 4.2.3 on 2023-07-13 15:36

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0020_remove_footerlinks_footer_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlinks',
            old_name='footer_link_name',
            new_name='link_name',
        ),
        migrations.RenameField(
            model_name='footerlinks',
            old_name='footer_link_text',
            new_name='link_text',
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='header',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='testblog.header'),
            preserve_default=False,
        ),
    ]
