# Generated by Django 4.2.3 on 2023-07-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0021_rename_footer_link_name_footerlinks_link_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Index Page', 'verbose_name_plural': 'Blog Index Pages'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
    ]
