# Generated by Django 4.2.3 on 2023-07-13 16:26

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0022_alter_blogindexpage_options_alter_blogpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinks',
            name='footer',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='testblog.footer'),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='header',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='testblog.header'),
        ),
    ]
