# Generated by Django 4.2.3 on 2023-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0025_footer_undertext_alter_footer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoToButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
