# Generated by Django 4.2.3 on 2023-07-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0030_herosection_navlinks_hero_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='subtext',
            new_name='subText',
        ),
    ]
