# Generated by Django 4.2.3 on 2023-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0031_rename_subtext_herosection_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlinks',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
