# Generated by Django 4.2.3 on 2023-07-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0032_navlinks_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
