# Generated by Django 4.2.3 on 2023-07-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('testblog', '0034_rename_blogpagetag_cryptopagetag_aitoolpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='CryptoPage',
        ),
        migrations.AlterModelOptions(
            name='cryptopage',
            options={'verbose_name': 'Crypto Product Page', 'verbose_name_plural': 'Crypto Product Pages'},
        ),
    ]
