# Generated by Django 4.2.3 on 2023-07-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('testblog', '0035_rename_blogpage_cryptopage_alter_cryptopage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='CatalogIndexPage',
        ),
        migrations.AlterModelOptions(
            name='catalogindexpage',
            options={'verbose_name': 'Catalog Index Page', 'verbose_name_plural': 'Catalog Index Pages'},
        ),
    ]
