# Generated by Django 4.2.3 on 2023-07-27 16:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0038_aitoolpagetag_alter_aitoolpage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bigText', models.CharField(blank=True, max_length=255, null=True)),
                ('subText', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('card_name', models.CharField(max_length=255)),
                ('card_text', models.CharField(max_length=255)),
                ('card_link', models.CharField(blank=True, max_length=255, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('AboutUs', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='testblog.aboutus')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
