# Generated by Django 4.2.3 on 2023-07-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0039_aboutus_featurecards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us section', 'verbose_name_plural': 'About Us sections'},
        ),
    ]
