# Generated by Django 4.2.3 on 2023-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0040_alter_aboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourAddHere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
