# Generated by Django 4.2.3 on 2023-07-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0042_youraddhere_link_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourAddHere',
            new_name='YourAdHere',
        ),
    ]
