# Generated by Django 4.2.3 on 2023-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0043_rename_youraddhere_youradhere'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitoolpage',
            name='open_for_ads',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cryptopage',
            name='open_for_ads',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
