# Generated by Django 4.2.3 on 2023-07-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0044_aitoolpage_open_for_ads_cryptopage_open_for_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenForAdWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
