# Generated by Django 4.2.3 on 2023-07-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0045_openforadwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='openforadwork',
            name='Texture_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
