# Generated by Django 4.2.3 on 2023-07-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0046_openforadwork_texture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openforadwork',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='openforadwork',
            old_name='Texture_Image',
            new_name='texture_image',
        ),
    ]
