# Generated by Django 4.2.3 on 2023-07-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('testblog', '0047_rename_image_openforadwork_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogindexpage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Catalog Page',
                'verbose_name_plural': 'Catalog Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
