# Generated by Django 4.2.3 on 2023-07-30 14:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0048_catalogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
