# Generated by Django 4.2.4 on 2023-08-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0051_cardssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
