# Generated by Django 4.2.4 on 2023-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0052_tagssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagssection',
            name='title',
            field=models.CharField(default='DefaultTitle', max_length=255),
        ),
    ]
