# Generated by Django 4.2.4 on 2023-08-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0053_tagssection_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsSection',
        ),
    ]
