# Generated by Django 4.2.4 on 2023-08-11 07:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0055_aitoolpage_popularity_cryptopage_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add your text', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
