# Generated by Django 4.2.4 on 2023-08-11 08:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0057_alter_cryptopage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopage',
            name='content',
            field=wagtail.fields.StreamField([('faselitet', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock())]))], default=[('faselitet', {'text': 'Ting 2', 'title': 'Ting'}), ('faselitet', {'text': 'TAng 2', 'title': 'TAng'})], use_json_field=True),
        ),
    ]
