# Generated by Django 4.2.4 on 2023-08-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0065_alter_cryptopage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptopage',
            name='content',
        ),
    ]
