# Generated by Django 4.2.4 on 2023-08-11 09:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0068_remove_cryptopage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopage',
            name='extraStream',
            field=wagtail.fields.StreamField([('extra', wagtail.blocks.CharBlock(help_text='add you char block', required=True))], blank=True, null=True, use_json_field=True),
        ),
    ]
