# Generated by Django 4.2.4 on 2023-08-11 09:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0069_cryptopage_extrastream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopage',
            name='extraStream',
            field=wagtail.fields.StreamField([('extra', wagtail.blocks.CharBlock(help_text='add you char block', required=True))], blank=True, default=[('extra', 'Here is the default')], null=True, use_json_field=True),
        ),
    ]
