# Generated by Django 4.2.4 on 2023-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0070_alter_cryptopage_extrastream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptopage',
            old_name='extraStream',
            new_name='content',
        ),
    ]
