# Generated by Django 4.2.4 on 2023-08-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('testblog', '0072_alter_cryptopage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopage',
            name='default_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
