# Generated by Django 4.2.4 on 2023-08-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0076_defaultimagespicker_defaultimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptopage',
            name='default_image',
        ),
    ]
