# Generated by Django 4.2.4 on 2023-08-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0082_alter_cryptopage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultImages',
        ),
        migrations.DeleteModel(
            name='DefaultImagesPicker',
        ),
    ]
