# Generated by Django 4.2.4 on 2023-08-13 08:25

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0089_alter_cryptopage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopage',
            name='content',
            field=wagtail.fields.StreamField([('ImageWithCaption', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(default=7, help_text='Add your Image', required=True)), ('caption', wagtail.blocks.TextBlock(default='default text', help_text='Add your caption', required=False))], help_text='add you char block', required=False)), ('ImageAndVideo', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(help_text='Add your Video', required=False))], equired=False, help_text='add you images and videos to a block'))], blank=True, null=True, use_json_field=True),
        ),
    ]
