# Generated by Django 4.2.4 on 2023-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0093_alter_cryptopage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopage',
            name='product_link',
            field=models.URLField(default='https://a-ads.com'),
        ),
    ]
