# Generated by Django 4.2.4 on 2023-08-13 14:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0094_cryptopage_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseHere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('main_text', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_link', models.CharField(blank=True, max_length=255, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('AdvertiseHere', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_items', to='testblog.advertisehere')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
