# Generated by Django 4.2.4 on 2023-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0096_relatedsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedSection',
        ),
    ]
