# Generated by Django 4.2.4 on 2023-08-14 15:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('testblog', '0098_cryptopage_related_page_1_cryptopage_related_page_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitoolpage',
            name='content',
            field=wagtail.fields.StreamField([('ImageWithCaption', wagtail.blocks.StructBlock([('image_width', wagtail.blocks.ChoiceBlock(choices=[('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], help_text='Set image width in percent', icon='cogs')), ('image', wagtail.images.blocks.ImageChooserBlock(default=7, help_text='Add your Image', required=True)), ('caption', wagtail.blocks.TextBlock(default='default text', help_text='Add your caption', required=False))], help_text='add you char block', required=False)), ('ImageAndVideo', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(help_text='Add your Video', required=False))], help_text='add you images and videos to a block', required=False)), ('RichText', wagtail.blocks.RichTextBlock(help_text='add you Rich Text block', required=False))], blank=True, default=[], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='aitoolpage',
            name='product_link',
            field=models.URLField(default='https://a-ads.com'),
        ),
        migrations.AddField(
            model_name='aitoolpage',
            name='related_page_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='aitoolpage',
            name='related_page_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='aitoolpage',
            name='related_page_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
